### ISSUE TITLE
Support LodeWallet

### ISSUE THREAD

**Issue by wolf31o2** [TosiDrop/vm-frontend#231] opened 2022-08-16 23:55 UTC

**Comment by reqlez** [comment] 2022-09-21 17:06
Already spoke to their team. When I tested using their "Nami" wallet injection, the TXes would go thru, but on our client side would say failed.

They recommended to add support for "cardano.LodeWallet"  and test again. If this does not work, I will go back to them to see what is going on.

**Comment by reqlez** [comment] 2022-11-21 05:15
Last time I tested, there was a white screen after TX submission, however, wallet dev mentioned the issue is on their side + the TX actually works. Closing as completed.

**Closed by reqlez** 2022-11-21 05:15 UTC
Labels: enhancement, good first issue
