### ISSUE TITLE
On 304, results show as empty

### ISSUE THREAD

**Issue by wolf31o2** [TosiDrop/vm-frontend#84] opened 2022-04-28 15:10 UTC
After checking rewards once.... Click on Aidrop, then back to Claim. Wallet is still connected, but checking rewards returns a 304, which is not interpreted correctly. In the screenshot, you can see I have 18 rewards available.
![image](https://user-images.githubusercontent.com/380021/165784634-a30349c5-248d-408c-a459-130e9ad89c96.png)

**Comment by aryelciu001** [comment] 2022-05-06 15:52
maybe it is just a one time thing OR it might be fixed with the code from elsewhere. I can't reproduce the error

**Closed by aryelciu001** 2022-05-06 15:52 UTC
